spring:
  application:
    name: chat
server:
  port: 8005

eureka:
  instance:
    prefer-ip-address: true #注册服务时使用ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jfinal:
  debug: true
  jdbcUrl: jdbc:mysql://47.104.5.214:3306/wuhvote?characterEncoding=utf8&serverTimezone=UTC
  dbUser: wuhvote
  dbPwd: wuhvote...2018