package com.cross2u.ware.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {

        arp.addMapping("abevalreport", "aerId", Abevalreport.class);
		arp.addMapping("abnormalgoodsinfo", "agiId", Abnormalgoodsinfo.class);
		arp.addMapping("atrribute", "atId", Atrribute.class);
		arp.addMapping("attributeoption", "aoId", Attributeoption.class);
		arp.addMapping("bevalreply", "berId", Bevalreply.class);
		arp.addMapping("category", "ctId", Category.class);
		arp.addMapping("categoryattribute", "caId", Categoryattribute.class);
		arp.addMapping("categoryformat", "cfId", Categoryformat.class);
		arp.addMapping("evalware", "ewId", Evalware.class);
		arp.addMapping("format", "fId", Format.class);
		arp.addMapping("formatoption", "foId", Formatoption.class);
		arp.addMapping("product", "pId", Product.class);
		arp.addMapping("productformat", "pfId", Productformat.class);
		arp.addMapping("ware", "wId", Ware.class);
		arp.addMapping("wareattribute", "waId", Wareattribute.class);
		arp.addMapping("stock", "skId", Stock.class);
	}
}

