package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseAbevalreport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Abevalreport extends BaseAbevalreport<Abevalreport> {
	public static final Abevalreport dao = new Abevalreport().dao();
}
