package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseAdminreply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Adminreply extends BaseAdminreply<Adminreply> {
	public static final Adminreply dao = new Adminreply().dao();
}
