package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseAmchart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Amchart extends BaseAmchart<Amchart> {
	public static final Amchart dao = new Amchart().dao();
}
