package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseBrowserecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Browserecord extends BaseBrowserecord<Browserecord> {
	public static final Browserecord dao = new Browserecord().dao();
}
