package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Business extends BaseBusiness<Business> {
	public static final Business dao = new Business().dao();
}
