package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseCategoryformat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Categoryformat extends BaseCategoryformat<Categoryformat> {
	public static final Categoryformat dao = new Categoryformat().dao();
}
