package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseEvalware;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Evalware extends BaseEvalware<Evalware> {
	public static final Evalware dao = new Evalware().dao();
}
