package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseIndent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Indent extends BaseIndent<Indent> {
	public static final Indent dao = new Indent().dao();
}
