package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseMbchat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mbchat extends BaseMbchat<Mbchat> {
	public static final Mbchat dao = new Mbchat().dao();
}
