package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseMevalreply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mevalreply extends BaseMevalreply<Mevalreply> {
	public static final Mevalreply dao = new Mevalreply().dao();
}
