package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseOutindent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Outindent extends BaseOutindent<Outindent> {
	public static final Outindent dao = new Outindent().dao();
}
