package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseReportmanufacturereasons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reportmanufacturereasons extends BaseReportmanufacturereasons<Reportmanufacturereasons> {
	public static final Reportmanufacturereasons dao = new Reportmanufacturereasons().dao();
}
