package com.cross2u.ware.model;

import com.cross2u.ware.model.base.BaseReturncatalog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Returncatalog extends BaseReturncatalog<Returncatalog> {
	public static final Returncatalog dao = new Returncatalog().dao();
}
