package com.cross2u.ware.model;


import com.cross2u.ware.model.base.BaseSensitive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sensitive extends BaseSensitive<Sensitive> {
	public static final Sensitive dao = new Sensitive().dao();
}
