spring:
  application:
    name: ware
server:
  port: 8003

eureka:
  instance:
    prefer-ip-address: true #注册服务时使用ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

jfinal:
  debug: true
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/cross2u?characterEncoding=utf8&serverTimezone=UTC
  dbUser: root
  dbPwd: '!yue980122M!'