package com.cross2u.manage.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {

		arp.addMapping("adminkeyword", "akId", Adminkeyword.class);
		arp.addMapping("adminreply", "arId", Adminreply.class);
		arp.addMapping("drawbackreasons", "drId", Drawbackreasons.class);
		arp.addMapping("publicinfo", "piId", Publicinfo.class);
		arp.addMapping("reportevaluatereasons", "rerId", Reportevaluatereasons.class);
		arp.addMapping("reportmanufacturereasons", "rmrId", Reportmanufacturereasons.class);
		arp.addMapping("sensitive", "senId", Sensitive.class);
	}
}

