package com.cross2u.manage.model;

import com.cross2u.manage.model.base.BaseDrawbackreasons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Drawbackreasons extends BaseDrawbackreasons<Drawbackreasons> {
	public static final Drawbackreasons dao = new Drawbackreasons().dao();
}
