package com.cross2u.manage.model;


import com.cross2u.manage.model.base.BaseReportgoodreasons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reportgoodreasons extends BaseReportgoodreasons<Reportgoodreasons> {
	public static final Reportgoodreasons dao = new Reportgoodreasons().dao();
}
