package com.cross2u.manage.model;

import com.cross2u.manage.model.base.BaseReportevaluatereasons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reportevaluatereasons extends BaseReportevaluatereasons<Reportevaluatereasons> {
	public static final Reportevaluatereasons dao = new Reportevaluatereasons().dao();
}
