package com.cross2u.manage.model;

import com.cross2u.manage.model.base.BaseSensitive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sensitive extends BaseSensitive<Sensitive> {
	public static final Sensitive dao = new Sensitive().dao();
}
