package com.cross2u.manage.model;

import com.cross2u.manage.model.base.BaseSensi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sensi extends BaseSensi<Sensi> {
	public static final Sensi dao = new Sensi().dao();
}
