package com.cross2u.indent.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCooperation<M extends BaseCooperation<M>> extends Model<M> implements IBean {

	public void setCopId(java.math.BigInteger copId) {
		set("copId", copId);
	}

	public java.math.BigInteger getCopId() {
		return get("copId");
	}

	public void setCopBId(Long copBId) {
		set("copBId", copBId);
	}

	public Long getCopBId() {
		return get("copBId");
	}

	public void setCopSId(Long copSId) {
		set("copSId", copSId);
	}

	public Long getCopSId() {
		return get("copSId");
	}

	public void setCopState(Integer copState) {
		set("copState", copState);
	}

	public Integer getCopState() {
		return get("copState");
	}

	public void setCopCreateTime(java.util.Date copCreateTime) {
		set("copCreateTime", copCreateTime);
	}

	public java.util.Date getCopCreateTime() {
		return get("copCreateTime");
	}

	public void setCopModifyTime(java.util.Date copModifyTime) {
		set("copModifyTime", copModifyTime);
	}

	public java.util.Date getCopModifyTime() {
		return get("copModifyTime");
	}

	public void setCopStar(Integer copStar) {
		set("copStar", copStar);
	}

	public Integer getCopStar() {
		return get("copStar");
	}

}
