package com.cross2u.indent.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCategoryformat<M extends BaseCategoryformat<M>> extends Model<M> implements IBean {

	public void setCfId(java.math.BigInteger cfId) {
		set("cfId", cfId);
	}

	public java.math.BigInteger getCfId() {
		return get("cfId");
	}

	public void setCfCategory(java.math.BigInteger cfCategory) {
		set("cfCategory", cfCategory);
	}

	public java.math.BigInteger getCfCategory() {
		return get("cfCategory");
	}

	public void setCfFormat(java.math.BigInteger cfFormat) {
		set("cfFormat", cfFormat);
	}

	public java.math.BigInteger getCfFormat() {
		return get("cfFormat");
	}

	public void setCfCreateTime(java.util.Date cfCreateTime) {
		set("cfCreateTime", cfCreateTime);
	}

	public java.util.Date getCfCreateTime() {
		return get("cfCreateTime");
	}

	public void setCfMdifyTime(java.util.Date cfMdifyTime) {
		set("cfMdifyTime", cfMdifyTime);
	}

	public java.util.Date getCfMdifyTime() {
		return get("cfMdifyTime");
	}

}
