package com.cross2u.indent.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDrawbackinfo<M extends BaseDrawbackinfo<M>> extends Model<M> implements IBean {

	public void setDiId(java.math.BigInteger diId) {
		set("diId", diId);
	}

	public java.math.BigInteger getDiId() {
		return get("diId");
	}

	public void setDiReporter(Long diReporter) {
		set("diReporter", diReporter);
	}

	public Long getDiReporter() {
		return get("diReporter");
	}

	public void setDiInId(Long diInId) {
		set("diInId", diInId);
	}

	public Long getDiInId() {
		return get("diInId");
	}

	public void setDiType(Long diType) {
		set("diType", diType);
	}

	public Long getDiType() {
		return get("diType");
	}

	public void setDiNUmber(Integer diNUmber) {
		set("diNUmber", diNUmber);
	}

	public Integer getDiNUmber() {
		return get("diNUmber");
	}

	public void setDiMoney(Float diMoney) {
		set("diMoney", diMoney);
	}

	public Float getDiMoney() {
		return get("diMoney");
	}

	public void setDiReasons(String diReasons) {
		set("diReasons", diReasons);
	}

	public String getDiReasons() {
		return get("diReasons");
	}

	public void setDiImg1(String diImg1) {
		set("diImg1", diImg1);
	}

	public String getDiImg1() {
		return get("diImg1");
	}

	public void setDiImg2(String diImg2) {
		set("diImg2", diImg2);
	}

	public String getDiImg2() {
		return get("diImg2");
	}

	public void setDiImg3(String diImg3) {
		set("diImg3", diImg3);
	}

	public String getDiImg3() {
		return get("diImg3");
	}

	public void setDiAId(Long diAId) {
		set("diAId", diAId);
	}

	public Long getDiAId() {
		return get("diAId");
	}

	public void setDiStatus(Integer diStatus) {
		set("diStatus", diStatus);
	}

	public Integer getDiStatus() {
		return get("diStatus");
	}

	public void setDiCreateTime(java.util.Date diCreateTime) {
		set("diCreateTime", diCreateTime);
	}

	public java.util.Date getDiCreateTime() {
		return get("diCreateTime");
	}

	public void setDiModifyTime(java.util.Date diModifyTime) {
		set("diModifyTime", diModifyTime);
	}

	public java.util.Date getDiModifyTime() {
		return get("diModifyTime");
	}

}
