package com.cross2u.indent.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuestion<M extends BaseQuestion<M>> extends Model<M> implements IBean {

	public void setQId(java.math.BigInteger qId) {
		set("qId", qId);
	}

	public java.math.BigInteger getQId() {
		return get("qId");
	}

	public void setQBusiness(java.math.BigInteger qBusiness) {
		set("qBusiness", qBusiness);
	}

	public java.math.BigInteger getQBusiness() {
		return get("qBusiness");
	}

	public void setQWare(java.math.BigInteger qWare) {
		set("qWare", qWare);
	}

	public java.math.BigInteger getQWare() {
		return get("qWare");
	}

	public void setQContent(String qContent) {
		set("qContent", qContent);
	}

	public String getQContent() {
		return get("qContent");
	}

	public void setQAnswerNum(java.math.BigInteger qAnswerNum) {
		set("qAnswerNum", qAnswerNum);
	}

	public java.math.BigInteger getQAnswerNum() {
		return get("qAnswerNum");
	}

	public void setQCreateTime(java.util.Date qCreateTime) {
		set("qCreateTime", qCreateTime);
	}

	public java.util.Date getQCreateTime() {
		return get("qCreateTime");
	}

	public void setQModifyTime(java.util.Date qModifyTime) {
		set("qModifyTime", qModifyTime);
	}

	public java.util.Date getQModifyTime() {
		return get("qModifyTime");
	}

}
