package com.cross2u.indent.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbnormalgoodsinfo<M extends BaseAbnormalgoodsinfo<M>> extends Model<M> implements IBean {

	public void setAgiId(java.math.BigInteger agiId) {
		set("agiId", agiId);
	}

	public java.math.BigInteger getAgiId() {
		return get("agiId");
	}

	public void setAgiReporter(Long agiReporter) {
		set("agiReporter", agiReporter);
	}

	public Long getAgiReporter() {
		return get("agiReporter");
	}

	public void setAgiWId(Long agiWId) {
		set("agiWId", agiWId);
	}

	public Long getAgiWId() {
		return get("agiWId");
	}

	public void setAgiType(Long agiType) {
		set("agiType", agiType);
	}

	public Long getAgiType() {
		return get("agiType");
	}

	public void setAgiReasons(String agiReasons) {
		set("agiReasons", agiReasons);
	}

	public String getAgiReasons() {
		return get("agiReasons");
	}

	public void setAgiIsAnymous(Integer agiIsAnymous) {
		set("agiIsAnymous", agiIsAnymous);
	}

	public Integer getAgiIsAnymous() {
		return get("agiIsAnymous");
	}

	public void setAgiAId(Long agiAId) {
		set("agiAId", agiAId);
	}

	public Long getAgiAId() {
		return get("agiAId");
	}

	public void setAgiResult(Integer agiResult) {
		set("agiResult", agiResult);
	}

	public Integer getAgiResult() {
		return get("agiResult");
	}

	public void setAgiCreateTime(java.util.Date agiCreateTime) {
		set("agiCreateTime", agiCreateTime);
	}

	public java.util.Date getAgiCreateTime() {
		return get("agiCreateTime");
	}

	public void setAgiModifyTime(java.util.Date agiModifyTime) {
		set("agiModifyTime", agiModifyTime);
	}

	public java.util.Date getAgiModifyTime() {
		return get("agiModifyTime");
	}

}
