package com.cross2u.indent.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScorerank<M extends BaseScorerank<M>> extends Model<M> implements IBean {

	public void setSrId(java.math.BigInteger srId) {
		set("srId", srId);
	}

	public java.math.BigInteger getSrId() {
		return get("srId");
	}

	public void setSrRank(Integer srRank) {
		set("srRank", srRank);
	}

	public Integer getSrRank() {
		return get("srRank");
	}

	public void setSrUp(Integer srUp) {
		set("srUp", srUp);
	}

	public Integer getSrUp() {
		return get("srUp");
	}

	public void setSrDown(Integer srDown) {
		set("srDown", srDown);
	}

	public Integer getSrDown() {
		return get("srDown");
	}

	public void setSrCreateTime(java.util.Date srCreateTime) {
		set("srCreateTime", srCreateTime);
	}

	public java.util.Date getSrCreateTime() {
		return get("srCreateTime");
	}

	public void setSrModifyTime(java.util.Date srModifyTime) {
		set("srModifyTime", srModifyTime);
	}

	public java.util.Date getSrModifyTime() {
		return get("srModifyTime");
	}

}
