package com.cross2u.indent.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollect<M extends BaseCollect<M>> extends Model<M> implements IBean {

	public void setCId(java.math.BigInteger cId) {
		set("cId", cId);
	}

	public java.math.BigInteger getCId() {
		return get("cId");
	}

	public void setCOwner(java.math.BigInteger cOwner) {
		set("cOwner", cOwner);
	}

	public java.math.BigInteger getCOwner() {
		return get("cOwner");
	}

	public void setCStore(java.math.BigInteger cStore) {
		set("cStore", cStore);
	}

	public java.math.BigInteger getCStore() {
		return get("cStore");
	}

	public void setCWare(java.math.BigInteger cWare) {
		set("cWare", cWare);
	}

	public java.math.BigInteger getCWare() {
		return get("cWare");
	}

	public void setCCreateTime(java.util.Date cCreateTime) {
		set("cCreateTime", cCreateTime);
	}

	public java.util.Date getCCreateTime() {
		return get("cCreateTime");
	}

	public void setCModifyTime(java.util.Date cModifyTime) {
		set("cModifyTime", cModifyTime);
	}

	public java.util.Date getCModifyTime() {
		return get("cModifyTime");
	}

}
