package com.cross2u.indent.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManufacturer<M extends BaseManufacturer<M>> extends Model<M> implements IBean {

	public void setMId(java.math.BigInteger mId) {
		set("mId", mId);
	}

	public java.math.BigInteger getMId() {
		return get("mId");
	}

	public void setMMainManu(java.math.BigInteger mMainManu) {
		set("mMainManu", mMainManu);
	}

	public java.math.BigInteger getMMainManu() {
		return get("mMainManu");
	}

	public void setMStatus(Integer mStatus) {
		set("mStatus", mStatus);
	}

	public Integer getMStatus() {
		return get("mStatus");
	}

	public void setMRank(Integer mRank) {
		set("mRank", mRank);
	}

	public Integer getMRank() {
		return get("mRank");
	}

	public void setMPhone(String mPhone) {
		set("mPhone", mPhone);
	}

	public String getMPhone() {
		return get("mPhone");
	}

	public void setMName(String mName) {
		set("mName", mName);
	}

	public String getMName() {
		return get("mName");
	}

	public void setMPassword(String mPassword) {
		set("mPassword", mPassword);
	}

	public String getMPassword() {
		return get("mPassword");
	}

	public void setMManageWare(Integer mManageWare) {
		set("mManageWare", mManageWare);
	}

	public Integer getMManageWare() {
		return get("mManageWare");
	}

	public void setMManageIndent(Integer mManageIndent) {
		set("mManageIndent", mManageIndent);
	}

	public Integer getMManageIndent() {
		return get("mManageIndent");
	}

	public void setMManageMessage(Integer mManageMessage) {
		set("mManageMessage", mManageMessage);
	}

	public Integer getMManageMessage() {
		return get("mManageMessage");
	}

	public void setMManageClient(Integer mManageClient) {
		set("mManageClient", mManageClient);
	}

	public Integer getMManageClient() {
		return get("mManageClient");
	}

	public void setMCreateTime(java.util.Date mCreateTime) {
		set("mCreateTime", mCreateTime);
	}

	public java.util.Date getMCreateTime() {
		return get("mCreateTime");
	}

	public void setMModifyTime(java.util.Date mModifyTime) {
		set("mModifyTime", mModifyTime);
	}

	public java.util.Date getMModifyTime() {
		return get("mModifyTime");
	}

}
