package com.cross2u.indent.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDelivertemp<M extends BaseDelivertemp<M>> extends Model<M> implements IBean {

	public void setDtId(java.math.BigInteger dtId) {
		set("dtId", dtId);
	}

	public java.math.BigInteger getDtId() {
		return get("dtId");
	}

	public void setDtOwner(java.math.BigInteger dtOwner) {
		set("dtOwner", dtOwner);
	}

	public java.math.BigInteger getDtOwner() {
		return get("dtOwner");
	}

	public void setDtName(String dtName) {
		set("dtName", dtName);
	}

	public String getDtName() {
		return get("dtName");
	}

	public void setDtSource(String dtSource) {
		set("dtSource", dtSource);
	}

	public String getDtSource() {
		return get("dtSource");
	}

	public void setDtCreateTime(java.util.Date dtCreateTime) {
		set("dtCreateTime", dtCreateTime);
	}

	public java.util.Date getDtCreateTime() {
		return get("dtCreateTime");
	}

	public void setDtModifyTime(java.util.Date dtModifyTime) {
		set("dtModifyTime", dtModifyTime);
	}

	public java.util.Date getDtModifyTime() {
		return get("dtModifyTime");
	}

}
