package com.cross2u.manage.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSensi<M extends BaseSensi<M>> extends Model<M> implements IBean {

	public void setSenId(BigInteger senId) {
		set("senId", senId);
	}

	public BigInteger getSenId() {
		return get("senId");
	}

	public void setSenText(String senText) {
		set("senText", senText);
	}

	public String getSenText() {
		return get("senText");
	}

	public void setSenReason(String senReason) {
		set("senReason", senReason);
	}

	public String getSenReason() {
		return get("senReason");
	}

	public void setSenAdministrator(BigInteger senAdministrator) {
		set("senAdministrator", senAdministrator);
	}

	public BigInteger getSenAdministrator() {
		return get("senAdministrator");
	}

	public void setSenCreateTime(java.util.Date senCreateTime) {
		set("senCreateTime", senCreateTime);
	}

	public java.util.Date getSenCreateTime() {
		return get("senCreateTime");
	}

	public void setSenModifyTime(java.util.Date senModifyTime) {
		set("senModifyTime", senModifyTime);
	}

	public java.util.Date getSenModifyTime() {
		return get("senModifyTime");
	}

}
