package com.cross2u.manage.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDrawbackreasons<M extends BaseDrawbackreasons<M>> extends Model<M> implements IBean {

	public void setDrId(BigInteger drId) {
		set("drId", drId);
	}

	public BigInteger getDrId() {
		return get("drId");
	}

	public void setDrReasons(String drReasons) {
		set("drReasons", drReasons);
	}

	public String getDrReasons() {
		return get("drReasons");
	}

	public void setDrDeduction(Integer drDeduction) {
		set("drDeduction", drDeduction);
	}

	public Integer getDrDeduction() {
		return get("drDeduction");
	}

	public void setDrCreateTime(java.util.Date drCreateTime) {
		set("drCreateTime", drCreateTime);
	}

	public java.util.Date getDrCreateTime() {
		return get("drCreateTime");
	}

	public void setDrModifyTime(java.util.Date drModifyTime) {
		set("drModifyTime", drModifyTime);
	}

	public java.util.Date getDrModifyTime() {
		return get("drModifyTime");
	}

}
