spring:
  application:
    name: store
server:
  port: 8006

eureka:
  instance:
    prefer-ip-address: true #注册服务时使用ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jfinal:
  debug: true
  jdbcUrl: jdbc:mysql://localhost:3306/cross2u?characterEncoding=utf8&serverTimezone=UTC
  dbUser: root
  dbPwd: password