spring:
  application:
    name: pay
server:
  port: 8004

eureka:
  instance:
    prefer-ip-address: true #注册服务时使用ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jfinal:
  debug: true
  jdbcUrl: jdbc:mysql://120.79.79.141:3306/cross2u?characterEncoding=utf8&serverTimezone=UTC
  dbUser: root
  dbPwd: 123456