server:
 port: 8761
eureka:
  instance:
    hostname: eureka-server #eureka实例的主机名
  client:
    register-with-eureka: false
    #不将自己注册到eureka上
    fetch-register: false
    #不从eureka上获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/