package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseAbchart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Abchart extends BaseAbchart<Abchart> {
	public static final Abchart dao = new Abchart().dao();
}
