package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseAbnormalgoodsinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Abnormalgoodsinfo extends BaseAbnormalgoodsinfo<Abnormalgoodsinfo> {
	public static final Abnormalgoodsinfo dao = new Abnormalgoodsinfo().dao();
}
