package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseAdministrator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Administrator extends BaseAdministrator<Administrator> {
	public static final Administrator dao = new Administrator().dao();
}
