package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseBevalreply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bevalreply extends BaseBevalreply<Bevalreply> {
	public static final Bevalreply dao = new Bevalreply().dao();
}
