package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseBusinesssearchrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Businesssearchrecord extends BaseBusinesssearchrecord<Businesssearchrecord> {
	public static final Businesssearchrecord dao = new Businesssearchrecord().dao();
}
