package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseCategoryattribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Categoryattribute extends BaseCategoryattribute<Categoryattribute> {
	public static final Categoryattribute dao = new Categoryattribute().dao();
}
