package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseCooperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cooperation extends BaseCooperation<Cooperation> {
	public static final Cooperation dao = new Cooperation().dao();
}
