package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseDelivertemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Delivertemp extends BaseDelivertemp<Delivertemp> {
	public static final Delivertemp dao = new Delivertemp().dao();
}
