package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseDrawbackinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Drawbackinfo extends BaseDrawbackinfo<Drawbackinfo> {
	public static final Drawbackinfo dao = new Drawbackinfo().dao();
}
