package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseManufacturer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Manufacturer extends BaseManufacturer<Manufacturer> {
	public static final Manufacturer dao = new Manufacturer().dao();
}
