package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseOutorderware;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Outorderware extends BaseOutorderware<Outorderware> {
	public static final Outorderware dao = new Outorderware().dao();
}
