package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseProductformat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Productformat extends BaseProductformat<Productformat> {
	public static final Productformat dao = new Productformat().dao();
}
