package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseReportgoodreasons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reportgoodreasons extends BaseReportgoodreasons<Reportgoodreasons> {
	public static final Reportgoodreasons dao = new Reportgoodreasons().dao();
}
