package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseReturngoodmould;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Returngoodmould extends BaseReturngoodmould<Returngoodmould> {
	public static final Returngoodmould dao = new Returngoodmould().dao();
}
