package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseReturngoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Returngoods extends BaseReturngoods<Returngoods> {
	public static final Returngoods dao = new Returngoods().dao();
}
