package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseSmsverification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Smsverification extends BaseSmsverification<Smsverification> {
	public static final Smsverification dao = new Smsverification().dao();
}
