package com.cross2u.user.model;

import com.cross2u.user.model.base.BaseWareattribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wareattribute extends BaseWareattribute<Wareattribute> {
	public static final Wareattribute dao = new Wareattribute().dao();
}
