spring:
  application:
    name: indent
server:
  port: 8002

eureka:
  instance:
    prefer-ip-address: true #注册服务时使用ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jfinal:
  debug: true
  #jdbcUrl: jdbc:mysql://120.79.79.141:3306/cross2u?characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/cross2u?characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true
  dbUser: root
  #dbPwd: 123456
    #jdbcUrl: jdbc:mysql://localhost:3306/cross2u?characterEncoding=utf8&serverTimezone=UTC
    #dbUser: root
  dbPwd: '!yue980122M!'

web3j:
  client-address: http://localhost:8545