package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBrowserecord<M extends BaseBrowserecord<M>> extends Model<M> implements IBean {

	public void setBrId(java.math.BigInteger brId) {
		set("brId", brId);
	}

	public java.math.BigInteger getBrId() {
		return get("brId");
	}

	public void setBrOwner(java.math.BigInteger brOwner) {
		set("brOwner", brOwner);
	}

	public java.math.BigInteger getBrOwner() {
		return get("brOwner");
	}

	public void setBrWare(java.math.BigInteger brWare) {
		set("brWare", brWare);
	}

	public java.math.BigInteger getBrWare() {
		return get("brWare");
	}

	public void setBrIsDelete(Integer brIsDelete) {
		set("brIsDelete", brIsDelete);
	}

	public Integer getBrIsDelete() {
		return get("BrIsDelete");
	}

	public void setBrCreateTime(java.util.Date brCreateTime) {
		set("brCreateTime", brCreateTime);
	}

	public java.util.Date getBrCreateTime() {
		return get("brCreateTime");
	}

	public void setBrModifyTime(java.util.Date brModifyTime) {
		set("brModifyTime", brModifyTime);
	}

	public java.util.Date getBrModifyTime() {
		return get("brModifyTime");
	}

}
