package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminkeyword<M extends BaseAdminkeyword<M>> extends Model<M> implements IBean {

	public void setAkId(java.math.BigInteger akId) {
		set("akId", akId);
	}

	public java.math.BigInteger getAkId() {
		return get("akId");
	}

	public void setAkText(String akText) {
		set("akText", akText);
	}

	public String getAkText() {
		return get("akText");
	}

	public void setAkReply(String akReply) {
		set("akReply", akReply);
	}

	public String getAkReply() {
		return get("akReply");
	}

	public void setAkAdministrator(Long akAdministrator) {
		set("akAdministrator", akAdministrator);
	}

	public Long getAkAdministrator() {
		return get("akAdministrator");
	}

	public void setAkCreateTime(java.util.Date akCreateTime) {
		set("akCreateTime", akCreateTime);
	}

	public java.util.Date getAkCreateTime() {
		return get("akCreateTime");
	}

	public void setAkModifyTime(java.util.Date akModifyTime) {
		set("akModifyTime", akModifyTime);
	}

	public java.util.Date getAkModifyTime() {
		return get("akModifyTime");
	}

}
