package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReturngoodreasons<M extends BaseReturngoodreasons<M>> extends Model<M> implements IBean {

	public void setRgrId(java.math.BigInteger rgrId) {
		set("rgrId", rgrId);
	}

	public java.math.BigInteger getRgrId() {
		return get("rgrId");
	}

	public void setRgrReasons(String rgrReasons) {
		set("rgrReasons", rgrReasons);
	}

	public String getRgrReasons() {
		return get("rgrReasons");
	}

	public void setRgrRCId(Long rgrRCId) {
		set("rgrRCId", rgrRCId);
	}

	public Long getRgrRCId() {
		return get("rgrRCId");
	}

	public void setRgrCreateTime(java.util.Date rgrCreateTime) {
		set("rgrCreateTime", rgrCreateTime);
	}

	public java.util.Date getRgrCreateTime() {
		return get("rgrCreateTime");
	}

	public void setRgrModifyTime(java.util.Date rgrModifyTime) {
		set("rgrModifyTime", rgrModifyTime);
	}

	public java.util.Date getRgrModifyTime() {
		return get("rgrModifyTime");
	}

}
