package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWarefdispatch<M extends BaseWarefdispatch<M>> extends Model<M> implements IBean {

	public void setWfdId(java.math.BigInteger wfdId) {
		set("wfdId", wfdId);
	}

	public java.math.BigInteger getWfdId() {
		return get("wfdId");
	}

	public void setWfdName(String wfdName) {
		set("wfdName", wfdName);
	}

	public String getWfdName() {
		return get("wfdName");
	}

	public void setWfdSId(Long wfdSId) {
		set("wfdSId", wfdSId);
	}

	public Long getWfdSId() {
		return get("wfdSId");
	}

	public void setWfdSort(Integer wfdSort) {
		set("wfdSort", wfdSort);
	}

	public Integer getWfdSort() {
		return get("wfdSort");
	}

	public void setWfdCreateTime(java.util.Date wfdCreateTime) {
		set("wfdCreateTime", wfdCreateTime);
	}

	public java.util.Date getWfdCreateTime() {
		return get("wfdCreateTime");
	}

	public void setWfdModifyTime(java.util.Date wfdModifyTime) {
		set("wfdModifyTime", wfdModifyTime);
	}

	public java.util.Date getWfdModifyTime() {
		return get("wfdModifyTime");
	}

}
