package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReturncatalog<M extends BaseReturncatalog<M>> extends Model<M> implements IBean {

	public void setRcId(java.math.BigInteger rcId) {
		set("rcId", rcId);
	}

	public java.math.BigInteger getRcId() {
		return get("rcId");
	}

	public void setRcCatalog(Integer rcCatalog) {
		set("rcCatalog", rcCatalog);
	}

	public Integer getRcCatalog() {
		return get("rcCatalog");
	}

	public void setRcDeduction(Integer rcDeduction) {
		set("rcDeduction", rcDeduction);
	}

	public Integer getRcDeduction() {
		return get("rcDeduction");
	}

	public void setRcCreateTime(java.util.Date rcCreateTime) {
		set("rcCreateTime", rcCreateTime);
	}

	public java.util.Date getRcCreateTime() {
		return get("rcCreateTime");
	}

	public void setRcModifyTime(java.util.Date rcModifyTime) {
		set("rcModifyTime", rcModifyTime);
	}

	public java.util.Date getRcModifyTime() {
		return get("rcModifyTime");
	}

}
