package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusinesssearchrecord<M extends BaseBusinesssearchrecord<M>> extends Model<M> implements IBean {

	public void setBsrId(BigInteger bsrId) {
		set("bsrId", bsrId);
	}

	public BigInteger getBsrId() {
		return get("bsrId");
	}

	public void setBsrBusiness(BigInteger bsrBusiness) {
		set("bsrBusiness", bsrBusiness);
	}

	public BigInteger getBsrBusiness() {
		return get("bsrBusiness");
	}

	public void setBsrContent(String bsrContent) {
		set("bsrContent", bsrContent);
	}

	public String getBsrContent() {
		return get("bsrContent");
	}

	public void setBsrCreateTime(java.util.Date bsrCreateTime) {
		set("bsrCreateTime", bsrCreateTime);
	}

	public java.util.Date getBsrCreateTime() {
		return get("bsrCreateTime");
	}

	public void setBsrModifyTime(java.util.Date bsrModifyTime) {
		set("bsrModifyTime", bsrModifyTime);
	}

	public java.util.Date getBsrModifyTime() {
		return get("bsrModifyTime");
	}

}
