package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbevalreport<M extends BaseAbevalreport<M>> extends Model<M> implements IBean {

	public void setAerId(java.math.BigInteger aerId) {
		set("aerId", aerId);
	}

	public java.math.BigInteger getAerId() {
		return get("aerId");
	}

	public void setAerFReportId(Long aerFReportId) {
		set("aerFReportId", aerFReportId);
	}

	public Long getAerFReportId() {
		return get("aerFReportId");
	}

	public void setAerType(Long aerType) {
		set("aerType", aerType);
	}

	public Long getAerType() {
		return get("aerType");
	}

	public void setAerContent(String aerContent) {
		set("aerContent", aerContent);
	}

	public String getAerContent() {
		return get("aerContent");
	}

	public void setAerState(Integer aerState) {
		set("aerState", aerState);
	}

	public Integer getAerState() {
		return get("aerState");
	}

	public void setAerAId(Long aerAId) {
		set("aerAId", aerAId);
	}

	public Long getAerAId() {
		return get("aerAId");
	}

	public void setAerCreateTime(java.util.Date aerCreateTime) {
		set("aerCreateTime", aerCreateTime);
	}

	public java.util.Date getAerCreateTime() {
		return get("aerCreateTime");
	}

	public void setAerModifyTime(java.util.Date aerModifyTime) {
		set("aerModifyTime", aerModifyTime);
	}

	public java.util.Date getAerModifyTime() {
		return get("aerModifyTime");
	}

}
