package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVisitor<M extends BaseVisitor<M>> extends Model<M> implements IBean {

	public void setVId(java.math.BigInteger vId) {
		set("vId", vId);
	}

	public java.math.BigInteger getVId() {
		return get("vId");
	}

	public void setVOpenId(String vOpenId) {
		set("vOpenId", vOpenId);
	}

	public String getVOpenId() {
		return get("vOpenId");
	}

	public void setVWeiXinIcon(String vWeiXinIcon) {
		set("vWeiXinIcon", vWeiXinIcon);
	}

	public String getVWeiXinIcon() {
		return get("vWeiXinIcon");
	}

	public void setVWeiXinName(String vWeiXinName) {
		set("vWeiXinName", vWeiXinName);
	}

	public String getVWeiXinName() {
		return get("vWeiXinName");
	}

	public void setVCreateTime(java.util.Date vCreateTime) {
		set("vCreateTime", vCreateTime);
	}

	public java.util.Date getVCreateTime() {
		return get("vCreateTime");
	}

	public void setVModifyTime(java.util.Date vModifyTime) {
		set("vModifyTime", vModifyTime);
	}

	public java.util.Date getVModifyTime() {
		return get("vModifyTime");
	}

}
