package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbnormalminfo<M extends BaseAbnormalminfo<M>> extends Model<M> implements IBean {

	public void setAmiId(java.math.BigInteger amiId) {
		set("amiId", amiId);
	}

	public java.math.BigInteger getAmiId() {
		return get("amiId");
	}

	public void setAmiReporter(Long amiReporter) {
		set("amiReporter", amiReporter);
	}

	public Long getAmiReporter() {
		return get("amiReporter");
	}

	public void setAmiMId(Long amiMId) {
		set("amiMId", amiMId);
	}

	public Long getAmiMId() {
		return get("amiMId");
	}

	public void setAmiType(Long amiType) {
		set("amiType", amiType);
	}

	public Long getAmiType() {
		return get("amiType");
	}

	public void setAmiReasons(String amiReasons) {
		set("amiReasons", amiReasons);
	}

	public String getAmiReasons() {
		return get("amiReasons");
	}

	public void setAmiIsAnymous(Integer amiIsAnymous) {
		set("amiIsAnymous", amiIsAnymous);
	}

	public Integer getAmiIsAnymous() {
		return get("amiIsAnymous");
	}

	public void setAgmiAId(Long agmiAId) {
		set("agmiAId", agmiAId);
	}

	public Long getAgmiAId() {
		return get("agmiAId");
	}

	public void setAgiResult(Integer agiResult) {
		set("agiResult", agiResult);
	}

	public Integer getAgiResult() {
		return get("agiResult");
	}

	public void setAgiCreateTime(java.util.Date agiCreateTime) {
		set("agiCreateTime", agiCreateTime);
	}

	public java.util.Date getAgiCreateTime() {
		return get("agiCreateTime");
	}

	public void setAgiModifyTime(java.util.Date agiModifyTime) {
		set("agiModifyTime", agiModifyTime);
	}

	public java.util.Date getAgiModifyTime() {
		return get("agiModifyTime");
	}

}
