package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigInteger;
import java.sql.Timestamp;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusiness<M extends BaseBusiness<M>> extends Model<M> implements IBean {

	public void setBId(java.math.BigInteger bId) {
		set("bId", bId);
	}

	public java.math.BigInteger getBId() {
		return get("bId");
	}

	public void setBName(String bName) {
		set("bName", bName);
	}

	public String getBName() {
		return get("bName");
	}

	public void setBPhone(String bPhone) {
		set("bPhone", bPhone);
	}

	public String getBPhone() {
		return get("bPhone");
	}

	public void setBEmail(String bEmail) {
		set("bEmail", bEmail);
	}

	public String getBEmail() {
		return get("bEmail");
	}

	public void setBIdNumber(String bIdNumber) {
		set("bIdNumber", bIdNumber);
	}

	public String getBIdNumber() {
		return get("bIdNumber");
	}

	public void setBRank(Integer bRank) {
		set("bRank", bRank);
	}

	public Integer getBRank() {
		return get("bRank");
	}

	public void setBMainBusiness(BigInteger bMainBusiness) {
		set("bMainBusiness", bMainBusiness);
	}

	public BigInteger getBMainBusiness() {
		return get("bMainBusiness");
	}

	public void setBScore(Integer bScore) {
		set("bScore", bScore);
	}

	public Integer getBScore() {
		return get("bScore");
	}

	public void setBStatus(Integer bStatus) {
		set("bStatus", bStatus);
	}

	public Integer getBStatus() {
		return get("bStatus");
	}

	public void setBOpenId(String bOpenId) {
		set("bOpenId", bOpenId);
	}

	public String getBOpenId() {
		return get("bOpenId");
	}

    public void setBWeiXinName(String bWeiXinName) {
        set("bWeiXinName", bWeiXinName);
    }

    public String getBWeiXinName() {
        return get("bWeiXinName");
    }

    public void setBWeiXinIcon(String bWeiXinIcon) {
        set("bWeiXinIcon", bWeiXinIcon);
    }

	public String getBWeiXinIcon() {
		return get("bWeiXinIcon");
	}

	public void setBIdUpImage(String bIdUpImage) {
		set("bIdUpImage", bIdUpImage);
	}

	public String getBIdUpImage() {
		return get("bIdUpImage");
	}

	public void setBIdDownImage(String bIdDownImage) {
		set("bIdDownImage", bIdDownImage);
	}

	public String getBIdDownImage() {
		return get("bIdDownImage");
	}

	public void setBOtherPlat1(Integer bOtherPlat1) {
		set("bOtherPlat1", bOtherPlat1);
	}

	public Integer getBOtherPlat1() {
		return get("bOtherPlat1");
	}

	public void setBOtherStore1(String bOtherStore1) {
		set("bOtherStore1", bOtherStore1);
	}

	public String getBOtherStore1() {
		return get("bOtherStore1");
	}

	public void setBOtherStatus1(Integer bOtherStatus1) {
		set("bOtherStatus1", bOtherStatus1);
	}

	public Integer getBOtherStatus1() {
		return get("bOtherStatus1");
	}

	public void setBOtherPlat2(Integer bOtherPlat2) {
		set("bOtherPlat2", bOtherPlat2);
	}

	public Integer getBOtherPlat2() {
		return get("bOtherPlat2");
	}

	public void setBOtherStore2(String bOtherStore2) {
		set("bOtherStore2", bOtherStore2);
	}

	public String getBOtherStore2() {
		return get("bOtherStore2");
	}

	public void setBOtherStatus2(Integer bOtherStatus2) {
		set("bOtherStatus2", bOtherStatus2);
	}

	public Integer getBOtherStatus2() {
		return get("bOtherStatus2");
	}

	public void setBOtherPlat3(Integer bOtherPlat3) {
		set("bOtherPlat3", bOtherPlat3);
	}

	public Integer getBOtherPlat3() {
		return get("bOtherPlat3");
	}

	public void setBOtherStore3(String bOtherStore3) {
		set("bOtherStore3", bOtherStore3);
	}

	public String getBOtherStore3() {
		return get("bOtherStore3");
	}

	public void setBOtherStatus3(Integer bOtherStatus3) {
		set("bOtherStatus3", bOtherStatus3);
	}

	public Integer getBOtherStatus3() {
		return get("bOtherStatus3");
	}

	public void setBFialReasonSelect(Integer bFialReasonSelect) {
		set("bFialReasonSelect", bFialReasonSelect);
	}

	public Integer getBFialReasonSelect() {
		return get("bFialReasonSelect");
	}

	public void setBFailReasonText(String bFailReasonText) {
		set("bFailReasonText", bFailReasonText);
	}

	public String getBFailReasonText() {
		return get("bFailReasonText");
	}

	public void setBAOperateTime(java.util.Date bAOperateTime) {
		set("bAOperateTime", bAOperateTime);
	}

	public java.util.Date getBAOperateTime() {
		return get("bAOperateTime");
	}

	public void setBCreateTime(Timestamp bCreateTime) {
		set("bCreateTime", bCreateTime);
	}

	public Timestamp getBCreateTime() {
		return get("bCreateTime");
	}

	public void setBModifyTime(java.util.Date bModifyTime) {
		set("bModifyTime", bModifyTime);
	}

	public java.util.Date getBModifyTime() {
		return get("bModifyTime");
	}

}
