package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOutorderware<M extends BaseOutorderware<M>> extends Model<M> implements IBean {

	public void setOowId(Integer oowId) {
		set("oowId", oowId);
	}

	public Integer getOowId() {
		return get("oowId");
	}

	public void setOowPIdentifier(String oowPIdentifier) {
		set("oowPIdentifier", oowPIdentifier);
	}

	public String getOowPIdentifier() {
		return get("oowPIdentifier");
	}

	public void setOowNumber(Integer oowNumber) {
		set("oowNumber", oowNumber);
	}

	public Integer getOowNumber() {
		return get("oowNumber");
	}

	public void setOowOutId(Long oowOutId) {
		set("oowOutId", oowOutId);
	}

	public Long getOowOutId() {
		return get("oowOutId");
	}

	public void setOowCreateTime(java.util.Date oowCreateTime) {
		set("oowCreateTime", oowCreateTime);
	}

	public java.util.Date getOowCreateTime() {
		return get("oowCreateTime");
	}

	public void setOowModifyTime(java.util.Date oowModifyTime) {
		set("oowModifyTime", oowModifyTime);
	}

	public java.util.Date getOowModifyTime() {
		return get("oowModifyTime");
	}

}
