package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbnormalminfo<M extends BaseAbnormalminfo<M>> extends Model<M> implements IBean {

	public void setAmiId(java.math.BigInteger amiId) {
		set("amiId", amiId);
	}

	public java.math.BigInteger getAmiId() {
		return get("amiId");
	}

	public void setAmiReporter(Long amiReporter) {
		set("amiReporter", amiReporter);
	}

	public Long getAmiReporter() {
		return get("amiReporter");
	}

	public void setAmiMId(Long amiMId) {
		set("amiMId", amiMId);
	}

	public Long getAmiMId() {
		return get("amiMId");
	}

	public void setAmiType(Long amiType) {
		set("amiType", amiType);
	}

	public Long getAmiType() {
		return get("amiType");
	}

	public void setAmiReasons(String amiReasons) {
		set("amiReasons", amiReasons);
	}

	public String getAmiReasons() {
		return get("amiReasons");
	}

	public void setAmiImg(String amiImg) {
		set("amiReasons", amiImg);
	}

	public String getAmiImg() {
		return get("amiImg");
	}

	public void setAmiIsAnymous(Integer amiIsAnymous) {
		set("amiIsAnymous", amiIsAnymous);
	}

	public Integer getAmiIsAnymous() {
		return get("amiIsAnymous");
	}

	public void setAmiAId(Long amiAId) {
		set("amiAId", amiAId);
	}

	public Long getAmiAId() {
		return get("amiAId");
	}

	public void setAmiResult(Integer amiResult) {
		set("amiResult", amiResult);
	}

	public Integer getAmiResult() {
		return get("amiResult");
	}

	public void setAmiCreateTime(java.util.Date amiCreateTime) {
		set("amiCreateTime", amiCreateTime);
	}

	public java.util.Date getAmiCreateTime() {
		return get("amiCreateTime");
	}

	public void setAmiModifyTime(java.util.Date amiModifyTime) {
		set("amiModifyTime", amiModifyTime);
	}

	public java.util.Date getAmiModifyTime() {
		return get("amiModifyTime");
	}

}
