package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBevalreply<M extends BaseBevalreply<M>> extends Model<M> implements IBean {

	public void setBerId(java.math.BigInteger berId) {
		set("berId", berId);
	}

	public java.math.BigInteger getBerId() {
		return get("berId");
	}

	public void setBerECId(BigInteger berECId) {
		set("berECId", berECId);
	}

	public BigInteger getBerECId() {
		return get("berECId");
	}

	public void setBerErId(BigInteger berErId) {
		set("berErId", berErId);
	}

	public BigInteger getBerErId() {
		return get("berErId");
	}

	public void setBerSpeaker(BigInteger berSpeaker) {
		set("berSpeaker", berSpeaker);
	}

	public BigInteger getBerSpeaker() {
		return get("berSpeaker");
	}

	public void setBerCotent(String berCotent) {
		set("berCotent", berCotent);
	}

	public String getBerCotent() {
		return get("berCotent");
	}

	public void setBerCreateTime(java.util.Date berCreateTime) {
		set("berCreateTime", berCreateTime);
	}

	public java.util.Date getBerCreateTime() {
		return get("berCreateTime");
	}

	public void setBerModifyTime(java.util.Date berModifyTime) {
		set("berModifyTime", berModifyTime);
	}

	public java.util.Date getBerModifyTime() {
		return get("berModifyTime");
	}

}
