package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusiness<M extends BaseBusiness<M>> extends Model<M> implements IBean {

	public void setBId(java.math.BigInteger bId) {
		set("bId", bId);
	}

	public java.math.BigInteger getBId() {
		return get("bId");
	}

	public void setBName(String bName) {
		set("bName", bName);
	}

	public String getBName() {
		return get("bName");
	}

	public void setBPassword(String bPassword) {
		set("bPassword", bPassword);
	}

	public String getBPassword() {
		return get("bPassword");
	}

	public void setBPhone(String bPhone) {
		set("bPhone", bPhone);
	}

	public String getBPhone() {
		return get("bPhone");
	}

	public void setBEmail(String bEmail) {
		set("bEmail", bEmail);
	}

	public String getBEmail() {
		return get("bEmail");
	}

	public void setBIdNumber(String bIdNumber) {
		set("bIdNumber", bIdNumber);
	}

	public String getBIdNumber() {
		return get("bIdNumber");
	}

	public void setBRank(Integer bRank) {
		set("bRank", bRank);
	}

	public Integer getBRank() {
		return get("bRank");
	}

	public void setBMainBusiness(Integer bMainBusiness) {
		set("bMainBusiness", bMainBusiness);
	}

	public Integer getBMainBusiness() {
		return get("bMainBusiness");
	}

	public void setBScore(Integer bScore) {
		set("bScore", bScore);
	}

	public Integer getBScore() {
		return get("bScore");
	}

}
