package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductformat<M extends BaseProductformat<M>> extends Model<M> implements IBean {

	public void setPfId(java.math.BigInteger pfId) {
		set("pfId", pfId);
	}

	public java.math.BigInteger getPfId() {
		return get("pfId");
	}

	public void setPfProduct(java.math.BigInteger pfProduct) {
		set("pfProduct", pfProduct);
	}

	public java.math.BigInteger getPfProduct() {
		return get("pfProduct");
	}

	public void setPfFormat(java.math.BigInteger pfFormat) {
		set("pfFormat", pfFormat);
	}

	public java.math.BigInteger getPfFormat() {
		return get("pfFormat");
	}

	public void setPfFormatOption(java.math.BigInteger pfFormatOption) {
		set("pfFormatOption", pfFormatOption);
	}

	public java.math.BigInteger getPfFormatOption() {
		return get("pfFormatOption");
	}

	public void setPfDefineOption(String pfDefineOption) {
		set("pfDefineOption", pfDefineOption);
	}

	public String getPfDefineOption() {
		return get("pfDefineOption");
	}

	public void setPfCreateTime(java.util.Date pfCreateTime) {
		set("pfCreateTime", pfCreateTime);
	}

	public java.util.Date getPfCreateTime() {
		return get("pfCreateTime");
	}

	public void setPfModifyTime(java.util.Date pfModifyTime) {
		set("pfModifyTime", pfModifyTime);
	}

	public java.util.Date getPfModifyTime() {
		return get("pfModifyTime");
	}

}
