package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusinesssearchrecord<M extends BaseBusinesssearchrecord<M>> extends Model<M> implements IBean {

	public void setBsrId(Integer bsrId) {
		set("bsrId", bsrId);
	}

	public Integer getBsrId() {
		return get("bsrId");
	}

	public void setBsrBusiness(Long bsrBusiness) {
		set("bsrBusiness", bsrBusiness);
	}

	public Long getBsrBusiness() {
		return get("bsrBusiness");
	}

	public void setBsrContent(String bsrContent) {
		set("bsrContent", bsrContent);
	}

	public String getBsrContent() {
		return get("bsrContent");
	}

	public void setBsrCreateTime(java.util.Date bsrCreateTime) {
		set("bsrCreateTime", bsrCreateTime);
	}

	public java.util.Date getBsrCreateTime() {
		return get("bsrCreateTime");
	}

	public void setBsrModifyTime(java.util.Date bsrModifyTime) {
		set("bsrModifyTime", bsrModifyTime);
	}

	public java.util.Date getBsrModifyTime() {
		return get("bsrModifyTime");
	}

	public void setBWeiXinIcon(String bWeiXinIcon){set("bWeiXinIcon",bWeiXinIcon);}

	public String getBWeiXinIcon(){return get("bWeiXinIcon");}

	public void setBWeiXinName(String bWeiXinName){set("bWeiXinName",bWeiXinName);}

	public String getBWeiXinName(){return get("bWeiXinName");}

}
