package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWarebelong<M extends BaseWarebelong<M>> extends Model<M> implements IBean {

	public void setWbId(java.math.BigInteger wbId) {
		set("wbId", wbId);
	}

	public java.math.BigInteger getWbId() {
		return get("wbId");
	}

	public void setWbWId(Long wbWId) {
		set("wbWId", wbWId);
	}

	public Long getWbWId() {
		return get("wbWId");
	}

	public void setWbWFDId(Long wbWFDId) {
		set("wbWFDId", wbWFDId);
	}

	public Long getWbWFDId() {
		return get("wbWFDId");
	}

	public void setWbWSDId(Long wbWSDId) {
		set("wbWSDId", wbWSDId);
	}

	public Long getWbWSDId() {
		return get("wbWSDId");
	}

	public void setWbCreateTime(java.util.Date wbCreateTime) {
		set("wbCreateTime", wbCreateTime);
	}

	public java.util.Date getWbCreateTime() {
		return get("wbCreateTime");
	}

	public void setWbModifyTime(java.util.Date wbModifyTime) {
		set("wbModifyTime", wbModifyTime);
	}

	public java.util.Date getWbModifyTime() {
		return get("wbModifyTime");
	}

}
