package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMainmanufacturer<M extends BaseMainmanufacturer<M>> extends Model<M> implements IBean {

	public void setMmId(java.math.BigInteger mmId) {
		set("mmId", mmId);
	}

	public java.math.BigInteger getMmId() {
		return get("mmId");
	}

	public void setMmStatus(Integer mmStatus) {
		set("mmStatus", mmStatus);
	}

	public Integer getMmStatus() {
		return get("mmStatus");
	}

	public void setMmStore(java.math.BigInteger mmStore) {
		set("mmStore", mmStore);
	}

	public java.math.BigInteger getMmStore() {
		return get("mmStore");
	}

	public void setMmName(String mmName) {
		set("mmName", mmName);
	}

	public String getMmName() {
		return get("mmName");
	}

	public void setMmPassword(String mmPassword) {
		set("mmPassword", mmPassword);
	}

	public String getMmPassword() {
		return get("mmPassword");
	}

	public void setMmPhone(String mmPhone) {
		set("mmPhone", mmPhone);
	}

	public String getMmPhone() {
		return get("mmPhone");
	}

	public void setMmEmail(String mmEmail) {
		set("mmEmail", mmEmail);
	}

	public String getMmEmail() {
		return get("mmEmail");
	}

	public void setMmCompany(String mmCompany) {
		set("mmCompany", mmCompany);
	}

	public String getMmCompany() {
		return get("mmCompany");
	}

	public void setMmtype(Integer mmtype) {
		set("mmtype", mmtype);
	}

	public Integer getMmtype() {
		return get("mmtype");
	}

	public void setMmLicence(String mmLicence) {
		set("mmLicence", mmLicence);
	}

	public String getMmLicence() {
		return get("mmLicence");
	}

	public void setMmCoIdentity(String mmCoIdentity) {
		set("mmCoIdentity", mmCoIdentity);
	}

	public String getMmCoIdentity() {
		return get("mmCoIdentity");
	}

	public void setMmValidityS(java.util.Date mmValidityS) {
		set("mmValidityS", mmValidityS);
	}

	public java.util.Date getMmValidityS() {
		return get("mmValidityS");
	}

	public void setMmValidityE(java.util.Date mmValidityE) {
		set("mmValidityE", mmValidityE);
	}

	public java.util.Date getMmValidityE() {
		return get("mmValidityE");
	}

	public void setMmLogo(String mmLogo) {
		set("mmLogo", mmLogo);
	}

	public String getMmLogo() {
		return get("mmLogo");
	}

	public void setMmOwner(String mmOwner) {
		set("mmOwner", mmOwner);
	}

	public String getMmOwner() {
		return get("mmOwner");
	}

	public void setMmIdNumber(String mmIdNumber) {
		set("mmIdNumber", mmIdNumber);
	}

	public String getMmIdNumber() {
		return get("mmIdNumber");
	}

	public void setMmIdUpImage(String mmIdUpImage) {
		set("mmIdUpImage", mmIdUpImage);
	}

	public String getMmIdUpImage() {
		return get("mmIdUpImage");
	}

	public void setMmIdDownImage(String mmIdDownImage) {
		set("mmIdDownImage", mmIdDownImage);
	}

	public String getMmIdDownImage() {
		return get("mmIdDownImage");
	}

	public void setMmMajorBusiness(String mmMajorBusiness) {
		set("mmMajorBusiness", mmMajorBusiness);
	}

	public String getMmMajorBusiness() {
		return get("mmMajorBusiness");
	}

	public void setMmFixedNum(String mmFixedNum) {
		set("mmFixedNum", mmFixedNum);
	}

	public String getMmFixedNum() {
		return get("mmFixedNum");
	}

	public void setMmCompanyPlace(String mmCompanyPlace) {
		set("mmCompanyPlace", mmCompanyPlace);
	}

	public String getMmCompanyPlace() {
		return get("mmCompanyPlace");
	}

	public void setMmCompanyContinent(Integer mmCompanyContinent) {
		set("mmCompanyContinent", mmCompanyContinent);
	}

	public Integer getMmCompanyContinent() {
		return get("mmCompanyContinent");
	}

	public void setMmEnsureMoney(java.math.BigInteger mmEnsureMoney) {
		set("mmEnsureMoney", mmEnsureMoney);
	}

	public java.math.BigInteger getMmEnsureMoney() {
		return get("mmEnsureMoney");
	}

	public void setMmEnsureMoneyUnit(Integer mmEnsureMoneyUnit) {
		set("mmEnsureMoneyUnit", mmEnsureMoneyUnit);
	}

	public Integer getMmEnsureMoneyUnit() {
		return get("mmEnsureMoneyUnit");
	}

	public void setMmFialReasonSelect(Integer mmFialReasonSelect) {
		set("mmFialReasonSelect", mmFialReasonSelect);
	}

	public Integer getMmFialReasonSelect() {
		return get("mmFialReasonSelect");
	}

	public void setMmFailReasonText(String mmFailReasonText) {
		set("mmFailReasonText", mmFailReasonText);
	}

	public String getMmFailReasonText() {
		return get("mmFailReasonText");
	}

	public void setMmCreateTime(java.util.Date mmCreateTime) {
		set("mmCreateTime", mmCreateTime);
	}

	public java.util.Date getMmCreateTime() {
		return get("mmCreateTime");
	}

	public void setMmModifyTime(java.util.Date mmModifyTime) {
		set("mmModifyTime", mmModifyTime);
	}

	public java.util.Date getMmModifyTime() {
		return get("mmModifyTime");
	}

}
