package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMevalreply<M extends BaseMevalreply<M>> extends Model<M> implements IBean {

	public void setMepId(Long mepId) {
		set("mepId", mepId);
	}

	public Long getMepId() {
		return get("mepId");
	}

	public void setMerMId(Long merMId) {
		set("merMId", merMId);
	}

	public Long getMerMId() {
		return get("merMId");
	}

	public void setMerEId(Long merEId) {
		set("merEId", merEId);
	}

	public Long getMerEId() {
		return get("merEId");
	}

	public void setMerCotent(String merCotent) {
		set("merCotent", merCotent);
	}

	public String getMerCotent() {
		return get("merCotent");
	}

	public void setMerCreateTime(java.util.Date merCreateTime) {
		set("merCreateTime", merCreateTime);
	}

	public java.util.Date getMerCreateTime() {
		return get("merCreateTime");
	}

	public void setMerModifyTime(java.util.Date merModifyTime) {
		set("merModifyTime", merModifyTime);
	}

	public java.util.Date getMerModifyTime() {
		return get("merModifyTime");
	}

}
