package com.cross2u.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIndent<M extends BaseIndent<M>> extends Model<M> implements IBean {

	public void setInId(BigInteger inId) {
		set("inId", inId);
	}

	public BigInteger getInId() {
		return get("inId");
	}

	public void setInNum(String inNum) {
		set("inNum", inNum);
	}

	public String getInNum() {
		return get("inNum");
	}

	public void setInBusiness(BigInteger inBusiness) {
		set("inBusiness", inBusiness);
	}

	public BigInteger getInBusiness() {
		return get("inBusiness");
	}

	public void setInStore(BigInteger inStore) {
		set("inStore", inStore);
	}

	public BigInteger getInStore() {
		return get("inStore");
	}

	public void setInWare(BigInteger inWare) {
		set("inWare", inWare);
	}

	public BigInteger getInWare() {
		return get("inWare");
	}

	public void setInProduct(BigInteger inProduct) {
		set("inProduct", inProduct);
	}

	public BigInteger getInProduct() {
		return get("inProduct");
	}

	public void setInTotalMoney(Float inTotalMoney) {
		set("inTotalMoney", inTotalMoney);
	}

	public Float getInTotalMoney() {
		return get("inTotalMoney");
	}

	public void setInProductNum(Integer inProductNum) {
		set("inProductNum", inProductNum);
	}

	public Integer getInProductNum() {
		return get("inProductNum");
	}

	public void setInLeftNum(Integer inLeftNum) {
		set("inLeftNum", inLeftNum);
	}

	public Integer getInLeftNum() {
		return get("inLeftNum");
	}

	public void setInStatus(Integer inStatus) {
		set("inStatus", inStatus);
	}

	public Integer getInStatus() {
		return get("inStatus");
	}

	public void setInMtoB(Integer inMtoB) {
		set("inMtoB", inMtoB);
	}

	public Integer getInMtoB() {
		return get("inMtoB");
	}

	public void setInBtoM(Integer inBtoM) {
		set("inBtoM", inBtoM);
	}

	public Integer getInBtoM() {
		return get("inBtoM");
	}

	public void setInPayTime(java.util.Date inPayTime) {
		set("inPayTime", inPayTime);
	}

	public java.util.Date getInPayTime() {
		return get("inPayTime");
	}

	public void setInCreateTime(java.util.Date inCreateTime) {
		set("inCreateTime", inCreateTime);
	}

	public java.util.Date getInCreateTime() {
		return get("inCreateTime");
	}

	public void setInModifyTime(java.util.Date inModifyTime) {
		set("inModifyTime", inModifyTime);
	}

	public java.util.Date getInModifyTime() {
		return get("inModifyTime");
	}

}
