package com.cross2u.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAtrribute<M extends BaseAtrribute<M>> extends Model<M> implements IBean {

	public void setAtId(java.math.BigInteger atId) {
		set("atId", atId);
	}

	public java.math.BigInteger getAtId() {
		return get("atId");
	}

	public void setAtChName(String atChName) {
		set("atChName", atChName);
	}

	public String getAtChName() {
		return get("atChName");
	}

	public void setAtEnName(String atEnName) {
		set("atEnName", atEnName);
	}

	public String getAtEnName() {
		return get("atEnName");
	}

	public void setAtName(String atName) {
		set("atName", atName);
	}

	public String getAtName() {
		return get("atName");
	}

	public void setAtCreateTime(java.util.Date atCreateTime) {
		set("atCreateTime", atCreateTime);
	}

	public java.util.Date getAtCreateTime() {
		return get("atCreateTime");
	}

	public void setAtModifyTime(java.util.Date atModifyTime) {
		set("atModifyTime", atModifyTime);
	}

	public java.util.Date getAtModifyTime() {
		return get("atModifyTime");
	}

}
