package com.cross2u.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbnormalgoodsinfo<M extends BaseAbnormalgoodsinfo<M>> extends Model<M> implements IBean {

	public void setAgiId(BigInteger agiId) {
		set("agiId", agiId);
	}

	public BigInteger getAgiId() {
		return get("agiId");
	}

	public void setAgiReporter(BigInteger agiReporter) {
		set("agiReporter", agiReporter);
	}

	public BigInteger getAgiReporter() {
		return get("agiReporter");
	}

	public void setAgiWId(BigInteger agiWId) {
		set("agiWId", agiWId);
	}

	public BigInteger getAgiWId() {
		return get("agiWId");
	}

	public void setAgiType(BigInteger agiType) {
		set("agiType", agiType);
	}

	public BigInteger getAgiType() {
		return get("agiType");
	}

	public void setAgiImg(String agiImg) {
		set("agiImg", agiImg);
	}

	public String getAgiImg() {
		return get("agiImg");
	}

	public void setAgiReasons(String agiReasons) {
		set("agiReasons", agiReasons);
	}

	public String getAgiReasons() {
		return get("agiReasons");
	}

	public void setAgiImg(String agiImg) {
		set("agiReasons", agiImg);
	}

	public String getAgiImg() {
		return get("agiImg");
	}

	public void setAgiIsAnymous(Integer agiIsAnymous) {
		set("agiIsAnymous", agiIsAnymous);
	}

	public Integer getAgiIsAnymous() {
		return get("agiIsAnymous");
	}

	public void setAgiAId(BigInteger agiAId) {
		set("agiAId", agiAId);
	}

	public BigInteger getAgiAId() {
		return get("agiAId");
	}

	public void setAgiResult(Integer agiResult) {
		set("agiResult", agiResult);
	}

	public Integer getAgiResult() {
		return get("agiResult");
	}

	public void setAgiCreateTime(java.util.Date agiCreateTime) {
		set("agiCreateTime", agiCreateTime);
	}

	public java.util.Date getAgiCreateTime() {
		return get("agiCreateTime");
	}

	public void setAgiModifyTime(java.util.Date agiModifyTime) {
		set("agiModifyTime", agiModifyTime);
	}

	public java.util.Date getAgiModifyTime() {
		return get("agiModifyTime");
	}

}
