package com.cross2u.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManukeyword<M extends BaseManukeyword<M>> extends Model<M> implements IBean {

	public void setMkId(java.math.BigInteger mkId) {
		set("mkId", mkId);
	}

	public java.math.BigInteger getMkId() {
		return get("mkId");
	}

	public void setMkText(String mkText) {
		set("mkText", mkText);
	}

	public String getMkText() {
		return get("mkText");
	}

	public void setMkReply(String mkReply) {
		set("mkReply", mkReply);
	}

	public String getMkReply() {
		return get("mkReply");
	}

	public void setMkManu(Long mkManu) {
		set("mkManu", mkManu);
	}

	public Long getMkManu() {
		return get("mkManu");
	}

	public void setMkCreateTime(java.util.Date mkCreateTime) {
		set("mkCreateTime", mkCreateTime);
	}

	public java.util.Date getMkCreateTime() {
		return get("mkCreateTime");
	}

	public void setMkModifyTime(java.util.Date mkModifyTime) {
		set("mkModifyTime", mkModifyTime);
	}

	public java.util.Date getMkModifyTime() {
		return get("mkModifyTime");
	}

}
