package com.cross2u.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOutindent<M extends BaseOutindent<M>> extends Model<M> implements IBean {

	public void setOutId(java.math.BigInteger outId) {
		set("outId", outId);
	}

	public java.math.BigInteger getOutId() {
		return get("outId");
	}

	public void setOutNumber(String outNumber) {
		set("outNumber", outNumber);
	}

	public String getOutNumber() {
		return get("outNumber");
	}

	public void setOutBusiness(Long outBusiness) {
		set("outBusiness", outBusiness);
	}

	public Long getOutBusiness() {
		return get("outBusiness");
	}

	public void setOutSId(Long outSId) {
		set("outSId", outSId);
	}

	public Long getOutSId() {
		return get("outSId");
	}

	public void setOutWIdentifier(String outWIdentifier) {
		set("outWIdentifier", outWIdentifier);
	}

	public String getOutWIdentifier() {
		return get("outWIdentifier");
	}

	public void setOutPlatform(Integer outPlatform) {
		set("outPlatform", outPlatform);
	}

	public Integer getOutPlatform() {
		return get("outPlatform");
	}

	public void setOutStore(String outStore) {
		set("outStore", outStore);
	}

	public String getOutStore() {
		return get("outStore");
	}

	public void setOutCName(String outCName) {
		set("outCName", outCName);
	}

	public String getOutCName() {
		return get("outCName");
	}

	public void setOutCPhone(String outCPhone) {
		set("outCPhone", outCPhone);
	}

	public String getOutCPhone() {
		return get("outCPhone");
	}

	public void setOutCAddress(String outCAddress) {
		set("outCAddress", outCAddress);
	}

	public String getOutCAddress() {
		return get("outCAddress");
	}

	public void setOutCInfo(String outCInfo) {
		set("outCInfo", outCInfo);
	}

	public String getOutCInfo() {
		return get("outCInfo");
	}

	public void setOutExpress(String outExpress) {
		set("outExpress", outExpress);
	}

	public String getOutExpress() {
		return get("outExpress");
	}

	public void setOutExpressCompany(String outExpressCompany) {
		set("outExpressCompany", outExpressCompany);
	}

	public String getOutExpressCompany() {
		return get("outExpressCompany");
	}

	public void setOutStatus(Integer outStatus) {
		set("outStatus", outStatus);
	}

	public Integer getOutStatus() {
		return get("outStatus");
	}

	public void setOutCreateTime(java.util.Date outCreateTime) {
		set("outCreateTime", outCreateTime);
	}

	public java.util.Date getOutCreateTime() {
		return get("outCreateTime");
	}

	public void setOutModifyTime(java.util.Date outModifyTime) {
		set("outModifyTime", outModifyTime);
	}

	public java.util.Date getOutModifyTime() {
		return get("outModifyTime");
	}

}
