package com.cross2u.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCategoryattribute<M extends BaseCategoryattribute<M>> extends Model<M> implements IBean {

	public void setCaId(java.math.BigInteger caId) {
		set("caId", caId);
	}

	public java.math.BigInteger getCaId() {
		return get("caId");
	}

	public void setCaCategory(java.math.BigInteger caCategory) {
		set("caCategory", caCategory);
	}

	public java.math.BigInteger getCaCategory() {
		return get("caCategory");
	}

	public void setCaAtrribute(java.math.BigInteger caAtrribute) {
		set("caAtrribute", caAtrribute);
	}

	public java.math.BigInteger getCaAtrribute() {
		return get("caAtrribute");
	}

	public void setCaCreateTime(java.util.Date caCreateTime) {
		set("caCreateTime", caCreateTime);
	}

	public java.util.Date getCaCreateTime() {
		return get("caCreateTime");
	}

	public void setCaModifyTime(java.util.Date caModifyTime) {
		set("caModifyTime", caModifyTime);
	}

	public java.util.Date getCaModifyTime() {
		return get("caModifyTime");
	}

}
