package com.cross2u.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setPId(java.math.BigInteger pId) {
		set("pId", pId);
	}

	public java.math.BigInteger getPId() {
		return get("pId");
	}

	public void setPIdentifier(String pIdentifier) {
		set("pIdentifier", pIdentifier);
	}

	public String getPIdentifier() {
		return get("pIdentifier");
	}

	public void setPWare(java.math.BigInteger pWare) {
		set("pWare", pWare);
	}

	public java.math.BigInteger getPWare() {
		return get("pWare");
	}

	public void setPMoney(Float pMoney) {
		set("pMoney", pMoney);
	}

	public Float getPMoney() {
		return get("pMoney");
	}

	public void setPMoneyUnit(Integer pMoneyUnit) {
		set("pMoneyUnit", pMoneyUnit);
	}

	public Integer getPMoneyUnit() {
		return get("pMoneyUnit");
	}

	public void setPStorage(java.math.BigInteger pStorage) {
		set("pStorage", pStorage);
	}

	public java.math.BigInteger getPStorage() {
		return get("pStorage");
	}

	public void setPImage(String pImage) {
		set("pImage", pImage);
	}

	public String getPImage() {
		return get("pImage");
	}

	public void setPCreateTime(java.util.Date pCreateTime) {
		set("pCreateTime", pCreateTime);
	}

	public java.util.Date getPCreateTime() {
		return get("pCreateTime");
	}

	public void setPModifyTime(java.util.Date pModifyTime) {
		set("pModifyTime", pModifyTime);
	}

	public java.util.Date getPModifyTime() {
		return get("pModifyTime");
	}

}
