package com.cross2u.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbevalreport<M extends BaseAbevalreport<M>> extends Model<M> implements IBean {

	public void setAerId(java.math.BigInteger aerId) {
		set("aerId", aerId);
	}

	public java.math.BigInteger getAerId() {
		return get("aerId");
	}

	public void setAerFReportId(BigInteger aerFReportId) {
		set("aerFReportId", aerFReportId);
	}

	public BigInteger getAerFReportId() {
		return get("aerFReportId");
	}

	public void setAerEWId(BigInteger aerEWId) {
		set("aerEWId", aerEWId);
	}

	public BigInteger getAerEWId() {
		return get("aerEWId");
	}

	public void setAerType(BigInteger aerType) {
		set("aerType", aerType);
	}

	public BigInteger getAerType() {
		return get("aerType");
	}

	public void setAerContent(String aerContent) {
		set("aerContent", aerContent);
	}

	public String getAerContent() {
		return get("aerContent");
	}

	public void setAerState(Integer aerState) {
		set("aerState", aerState);
	}

	public Integer getAerState() {
		return get("aerState");
	}

	public void setAerAId(BigInteger aerAId) {
		set("aerAId", aerAId);
	}

	public BigInteger getAerAId() {
		return get("aerAId");
	}

	public void setAerCreateTime(java.util.Date aerCreateTime) {
		set("aerCreateTime", aerCreateTime);
	}

	public java.util.Date getAerCreateTime() {
		return get("aerCreateTime");
	}

	public void setAerModifyTime(java.util.Date aerModifyTime) {
		set("aerModifyTime", aerModifyTime);
	}

	public java.util.Date getAerModifyTime() {
		return get("aerModifyTime");
	}

}
