package com.cross2u.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminreply<M extends BaseAdminreply<M>> extends Model<M> implements IBean {

	public void setArId(Long arId) {
		set("arId", arId);
	}

	public Long getArId() {
		return get("arId");
	}

	public void setArText(Integer arText) {
		set("arText", arText);
	}

	public Integer getArText() {
		return get("arText");
	}

	public void setArKeyword(String arKeyword) {
		set("arKeyword", arKeyword);
	}

	public String getArKeyword() {
		return get("arKeyword");
	}

	public void setArReply(String arReply) {
		set("arReply", arReply);
	}

	public String getArReply() {
		return get("arReply");
	}

	public void setArAdministrator(Long arAdministrator) {
		set("arAdministrator", arAdministrator);
	}

	public Long getArAdministrator() {
		return get("arAdministrator");
	}

	public void setArCreateTime(java.util.Date arCreateTime) {
		set("arCreateTime", arCreateTime);
	}

	public java.util.Date getArCreateTime() {
		return get("arCreateTime");
	}

	public void setArModifyTime(java.util.Date arModifyTime) {
		set("arModifyTime", arModifyTime);
	}

	public java.util.Date getArModifyTime() {
		return get("arModifyTime");
	}

}
