package com.cross2u.chat.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMbchat<M extends BaseMbchat<M>> extends Model<M> implements IBean {

	public void setMbchId(java.math.BigInteger mbchId) {
		set("mbchId", mbchId);
	}

	public java.math.BigInteger getMbchId() {
		return get("mbchId");
	}

	public void setMbchManu(BigInteger mbchManu) {
		set("mbchManu", mbchManu);
	}

	public BigInteger getMbchManu() {
		return get("mbchManu");
	}

	public void setMbchBusiness(BigInteger mbchBusiness) {
		set("mbchBusiness", mbchBusiness);
	}

	public BigInteger getMbchBusiness() {
		return get("mbchBusiness");
	}

	public void setMbchSpeaker(Integer mbchSpeaker) {
		set("mbchSpeaker", mbchSpeaker);
	}

	public Integer getMbchSpeaker() {
		return get("mbchSpeaker");
	}

	public void setMbchContent(String mbchContent) {
		set("mbchContent", mbchContent);
	}

	public String getMbchContent() {
		return get("mbchContent");
	}

	public void setMbchCreateTime(java.util.Date mbchCreateTime) {
		set("mbchCreateTime", mbchCreateTime);
	}

	public java.util.Date getMbchCreateTime() {
		return get("mbchCreateTime");
	}

	public void setMbchModifyTime(java.util.Date mbchModifyTime) {
		set("mbchModifyTime", mbchModifyTime);
	}

	public java.util.Date getMbchModifyTime() {
		return get("mbchModifyTime");
	}

}
