package com.cross2u.chat.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbchart<M extends BaseAbchart<M>> extends Model<M> implements IBean {

	public void setAbchId(java.math.BigInteger abchId) {
		set("abchId", abchId);
	}

	public java.math.BigInteger getAbchId() {
		return get("abchId");
	}

	public void setAbchBusiness(BigInteger abchBusiness) {
		set("abchBusiness", abchBusiness);
	}

	public BigInteger getAbchBusiness() {
		return get("abchBusiness");
	}

	public void setAbchAdministrator(BigInteger abchAdministrator) {
		set("abchAdministrator", abchAdministrator);
	}

	public BigInteger getAbchAdministrator() {
		return get("abchAdministrator");
	}

	public void setAbchSpeaker(Integer abchSpeaker) {
		set("abchSpeaker", abchSpeaker);
	}

	public Integer getAbchSpeaker() {
		return get("abchSpeaker");
	}

	public void setAbchContent(String abchContent) {
		set("abchContent", abchContent);
	}

	public String getAbchContent() {
		return get("abchContent");
	}

	public void setAbchCreateTime(java.util.Date abchCreateTime) {
		set("abchCreateTime", abchCreateTime);
	}

	public java.util.Date getAbchCreateTime() {
		return get("abchCreateTime");
	}

	public void setAbchModifyTime(java.util.Date abchModifyTime) {
		set("abchModifyTime", abchModifyTime);
	}

	public java.util.Date getAbchModifyTime() {
		return get("abchModifyTime");
	}

}
