package com.cross2u.chat.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public void setAacount(String aacount) {
		set("aacount", aacount);
	}

	public String getAacount() {
		return get("aacount");
	}

	public void setApassword(String apassword) {
		set("apassword", apassword);
	}

	public String getApassword() {
		return get("apassword");
	}

	public void setAcreate(java.util.Date acreate) {
		set("acreate", acreate);
	}

	public java.util.Date getAcreate() {
		return get("acreate");
	}

	public void setAmodified(java.util.Date amodified) {
		set("amodified", amodified);
	}

	public java.util.Date getAmodified() {
		return get("amodified");
	}

}
