package com.cross2u.store.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbnormalminfo<M extends BaseAbnormalminfo<M>> extends Model<M> implements IBean {

	public void setAmiId(java.math.BigInteger amiId) {
		set("amiId", amiId);
	}

	public java.math.BigInteger getAmiId() {
		return get("amiId");
	}

	public void setAmiReporter(BigInteger amiReporter) {
		set("amiReporter", amiReporter);
	}

	public BigInteger getAmiReporter() {
		return get("amiReporter");
	}

	public void setAmiSId(BigInteger amiSId) {
		set("amiSId", amiSId);
	}

	public BigInteger getAmiSId() {
		return get("amiSId");
	}

	public void setAmiType(BigInteger amiType) {
		set("amiType", amiType);
	}

	public BigInteger getAmiType() {
		return get("amiType");
	}

	public void setAmiReasons(String amiReasons) {
		set("amiReasons", amiReasons);
	}

	public String getAmiReasons() {
		return get("amiReasons");
	}

	public void setAmiImg(String amiImg) {
		set("amiImg", amiImg);
	}

	public String getAmiImg() {
		return get("amiImg");
	}

	public void setAmiIsAnymous(Integer amiIsAnymous) {
		set("amiIsAnymous", amiIsAnymous);
	}

	public Integer getAmiIsAnymous() {
		return get("amiIsAnymous");
	}

	public void setAmiAId(BigInteger amiAId) {
		set("amiAId", amiAId);
	}

	public BigInteger getAmiAId() {
		return get("amiAId");
	}

	public void setAmiResult(Integer amiResult) {
		set("amiResult", amiResult);
	}

	public Integer getAmiResult() {
		return get("amiResult");
	}

	public void setAmiCreateTime(java.util.Date amiCreateTime) {
		set("amiCreateTime", amiCreateTime);
	}

	public java.util.Date getAmiCreateTime() {
		return get("amiCreateTime");
	}

	public void setAmiModifyTime(java.util.Date amiModifyTime) {
		set("amiModifyTime", amiModifyTime);
	}

	public java.util.Date getAmiModifyTime() {
		return get("amiModifyTime");
	}

}
