package com.cross2u.store.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWaresdispatch<M extends BaseWaresdispatch<M>> extends Model<M> implements IBean {

	public void setWsdId(Long wsdId) {
		set("wsdId", wsdId);
	}

	public BigInteger getWsdId() {
		return get("wsdId");
	}

	public void setWsdWFDId(Long wsdWFDId) {
		set("wsdWFDId", wsdWFDId);
	}

	public Long getWsdWFDId() {
		return get("wsdWFDId");
	}

	public void setWsdName(String wsdName) {
		set("wsdName", wsdName);
	}

	public String getWsdName() {
		return get("wsdName");
	}

	public void setWsdImg(String wsdImg) {
		set("wsdImg", wsdImg);
	}

	public String getWsdImg() {
		return get("wsdImg");
	}

	public void setWsdSort(Integer wsdSort) {
		set("wsdSort", wsdSort);
	}

	public Integer getWsdSort() {
		return get("wsdSort");
	}

	public void setWsdCreateTime(java.util.Date wsdCreateTime) {
		set("wsdCreateTime", wsdCreateTime);
	}

	public java.util.Date getWsdCreateTime() {
		return get("wsdCreateTime");
	}

	public void setWsdModifyTime(java.util.Date wsdModifyTime) {
		set("wsdModifyTime", wsdModifyTime);
	}

	public java.util.Date getWsdModifyTime() {
		return get("wsdModifyTime");
	}

}
