package com.cross2u.store.model;

import com.cross2u.store.model.base.BaseScorerank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Scorerank extends BaseScorerank<Scorerank> {
	public static final Scorerank dao = new Scorerank().dao();
}
