package com.cross2u.store.model;

import com.cross2u.store.model.base.BaseWarebelong;
/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Warebelong extends BaseWarebelong<Warebelong> {
	public static final Warebelong dao = new Warebelong().dao();
}
