package com.cross2u.indent.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {

		arp.addMapping("drawbackinfo", "diId", Drawbackinfo.class);
		arp.addMapping("indent", "inId", Indent.class);
		arp.addMapping("outindent", "outId", Outindent.class);
		arp.addMapping("returncatalog", "rcId", Returncatalog.class);
		arp.addMapping("returngoodreasons", "rgrId", Returngoodreasons.class);
		arp.addMapping("returngoods", "rgId", Returngoods.class);

	}
}

