package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseAbnormalminfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Abnormalminfo extends BaseAbnormalminfo<Abnormalminfo> {
	public static final Abnormalminfo dao = new Abnormalminfo().dao();
}
