package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseAdminkeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Adminkeyword extends BaseAdminkeyword<Adminkeyword> {
	public static final Adminkeyword dao = new Adminkeyword().dao();
}
