package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseAtrribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Atrribute extends BaseAtrribute<Atrribute> {
	public static final Atrribute dao = new Atrribute().dao();
}
