package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseAttributeoption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attributeoption extends BaseAttributeoption<Attributeoption> {
	public static final Attributeoption dao = new Attributeoption().dao();
}
