package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseCollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collect extends BaseCollect<Collect> {
	public static final Collect dao = new Collect().dao();
}
