package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseDelivertemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Delivertemp extends BaseDelivertemp<Delivertemp> {
	public static final Delivertemp dao = new Delivertemp().dao();
}
