package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseEvaluatebonus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Evaluatebonus extends BaseEvaluatebonus<Evaluatebonus> {
	public static final Evaluatebonus dao = new Evaluatebonus().dao();
}
