package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseFormat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Format extends BaseFormat<Format> {
	public static final Format dao = new Format().dao();
}
