package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseFormatoption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Formatoption extends BaseFormatoption<Formatoption> {
	public static final Formatoption dao = new Formatoption().dao();
}
