package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseMainmanufacturer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mainmanufacturer extends BaseMainmanufacturer<Mainmanufacturer> {
	public static final Mainmanufacturer dao = new Mainmanufacturer().dao();
}
