package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseManukeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Manukeyword extends BaseManukeyword<Manukeyword> {
	public static final Manukeyword dao = new Manukeyword().dao();
}
