package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BasePublicinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Publicinfo extends BasePublicinfo<Publicinfo> {
	public static final Publicinfo dao = new Publicinfo().dao();
}
