package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseReturngoodreasons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Returngoodreasons extends BaseReturngoodreasons<Returngoodreasons> {
	public static final Returngoodreasons dao = new Returngoodreasons().dao();
}
