package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseReturngoodmould;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Returngoodmould extends BaseReturngoodmould<Returngoodmould> {
	public static final Returngoodmould dao = new Returngoodmould().dao();
}
