package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stock extends BaseStock<Stock> {
	public static final Stock dao = new Stock().dao();
}
