package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseStorebill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Storebill extends BaseStorebill<Storebill> {
	public static final Storebill dao = new Storebill().dao();
}
