package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseWarebonus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Warebonus extends BaseWarebonus<Warebonus> {
	public static final Warebonus dao = new Warebonus().dao();
}
