package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseWare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ware extends BaseWare<Ware> {
	public static final Ware dao = new Ware().dao();
}
