package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseWaresdispatch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Waresdispatch extends BaseWaresdispatch<Waresdispatch> {
	public static final Waresdispatch dao = new Waresdispatch().dao();
}
