package com.cross2u.indent.model;

import com.cross2u.indent.model.base.BaseWarefdispatch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Warefdispatch extends BaseWarefdispatch<Warefdispatch> {
	public static final Warefdispatch dao = new Warefdispatch().dao();
}
